#!/bin/sh
V=0.2.2

JGFSVD=~/.jgitflow-semver/$V;JGFSV=$JGFSVD/jgitflow-semver-$V.sh; ([ ! -f $JGFSV ] && mkdir -p $JGFSVD && \
    wget -q -O $JGFSV http://dl.bintray.com/cedric-vidal/jgitflow-semver/com/quicksign/jgitflow-semver/jgitflow-semver/$V/jgitflow-semver-$V-script.sh && \
    chmod a+x $JGFSV || exit 0)

rm ~/.jgitflow-semver/jgitflow-semver 2>/dev/null
ln -s $JGFSV ~/.jgitflow-semver/jgitflow-semver

export PATH=$PATH:~/.jgitflow-semver
